name: نشر منشورين يوميًا

on:
  schedule:
    # الشتاء (UTC+1): 23:00 في الجزائر = 22:00 UTC
    - cron: '0 22 * * *'   # المنشور الأول الساعة 22:00 UTC (11 مساءً بتوقيت الجزائر)
    - cron: '30 22 * * *'  # المنشور الثاني الساعة 22:30 UTC (11:30 مساءً بتوقيت الجزائر)

    # الصيف (UTC+2): 23:00 في الجزائر = 21:00 UTC
    # - cron: '0 21 * * *'   # قم بإلغاء التعليق إذا أردت التوقيت الصيفي
    # - cron: '30 21 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests
      
      - name: Run Posting Script
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
        run: python post_coupons.py
