name: نشر الكوبونات يوميًا محدث اليوم

on:
  schedule:
    # تشغيل يوميًا في تمام الساعة 00:00 بتوقيت UTC (يمكنك تعديل التوقيت)
    - cron:  '0 0 * * *'
  workflow_dispatch:  # للسماح بالتشغيل اليدوي أيضاً

jobs:
  post_coupons:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run posting script
      env:
        PAGE_ID: ${{ secrets.PAGE_ID }}
        PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
      run: python post_coupons.py
